# Generated by Django 3.2.5 on 2023-11-30 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_productimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='thumbnail',
        ),
    ]
